name: Gespeaker
pygments: true
author: Muflone
gitauthor: https://github.com/muflone
gitrepo: https://github.com/muflone/gespeaker
pathrepo: muflone/gespeaker
analytics-id: UA-44039396-1
resources-site: http://www.muflone.com/projects/gespeaker
